- job:
    name: devstack-plugin-ceph-tempest-base
    abstract: true
    parent: tempest-full
    description: |
      Base integration tests that runs with the ceph devstack plugin.
      Former names for this job where:
        * legacy-tempest-dsvm-full-devstack-plugin-ceph
        * gate-tempest-dsvm-full-devstack-plugin-ceph-ubuntu-xenial
      The original job included support for an un-used tempest-conf.sh:
        # If an in-repo configuration exists, source it.  This will likely
        # override DEVSTACK_GATE_TEMPEST_REGEX to further refine the set of
        # tests being run.
    required-projects:
      - openstack/cinder-tempest-plugin
      - openstack/devstack-plugin-ceph
    irrelevant-files: &irrelevant-files
      - ^.*\.rst$
      - ^doc/.*$
      - ^tox.ini$
    timeout: 7200
    vars:
      devstack_plugins:
        devstack-plugin-ceph: https://opendev.org/openstack/devstack-plugin-ceph
      devstack_localrc:
        ENABLE_FILE_INJECTION: false
        TEMPEST_PLUGINS: '/opt/stack/cinder-tempest-plugin'
        ENABLE_VOLUME_MULTIATTACH: false
        TEMPEST_RUN_VALIDATION: false
      tox_envlist: all
      tempest_test_regex: |
              (^tempest\.(api|scenario\.test_encrypted_cinder_volumes|scenario\.test_volume|scenario\.test_shelve_instance)|(^cinder_tempest_plugin))
      tempest_test_blacklist: '{{ ansible_user_dir }}/{{ zuul.projects["opendev.org/openstack/devstack-plugin-ceph"].src_dir }}/tempest_blacklist.txt'

- job:
    name: devstack-plugin-ceph-tempest
    parent: devstack-plugin-ceph-tempest-base
    description: |
      Integration tests that runs with the ceph devstack plugin and py27.
    branches:
      - stable/ocata
      - stable/pike
      - stable/queens
      - stable/rocky
    vars:
      devstack_localrc:
        CEPH_RELEASE: "luminous"

- job:
    name: devstack-plugin-ceph-tempest
    parent: devstack-plugin-ceph-tempest-base
    description: |
      Integration tests that runs with the ceph devstack plugin and py27.

      This job enable the multiattach feature enable from stein on.

    # This job runs with multiattach enable from stable/stein on.
    branches:
      - stable/stein
      - stable/train
    vars:
      devstack_localrc:
        ENABLE_VOLUME_MULTIATTACH: true
        CEPH_RELEASE: "nautilus"

- job:
    name: devstack-plugin-ceph-tempest-py3-base
    abstract: true
    parent: tempest-full-py3
    description: |
      Base integration tests that runs with the ceph devstack plugin and py3.
      Former names for this job where:
        * legacy-tempest-dsvm-py35-full-devstack-plugin-ceph
        * gate-tempest-dsvm-py35-full-devstack-plugin-ceph-ubuntu-xenial-nv
      The original job included support for an un-used tempest-dsvm-ceph-rc
      hosted at /opt/stack/new/nova/devstack/tempest-dsvm-ceph-rc.
    required-projects:
      - openstack/cinder-tempest-plugin
      - openstack/devstack-plugin-ceph
    irrelevant-files: *irrelevant-files
    timeout: 7200
    vars:
      devstack_localrc:
        ENABLE_FILE_INJECTION: false
        TEMPEST_PLUGINS: '/opt/stack/cinder-tempest-plugin'
        ENABLE_VOLUME_MULTIATTACH: false
        TEMPEST_RUN_VALIDATION: false
      devstack_plugins:
        devstack-plugin-ceph: https://opendev.org/openstack/devstack-plugin-ceph
      tox_envlist: all
      tempest_test_regex: |
              (^tempest\.(api|scenario\.test_encrypted_cinder_volumes|scenario\.test_volume|scenario\.test_shelve_instance)|(^cinder_tempest_plugin))
      tempest_test_blacklist: '{{ ansible_user_dir }}/{{ zuul.projects["opendev.org/openstack/devstack-plugin-ceph"].src_dir }}/tempest_blacklist.txt'

- job:
    name: devstack-plugin-ceph-tempest-py3
    parent: devstack-plugin-ceph-tempest-py3-base
    description: |
      Integration tests that runs with the ceph devstack plugin and py3.
    branches:
      - stable/ocata
      - stable/pike
      - stable/queens
      - stable/rocky
    vars:
      devstack_localrc:
        CEPH_RELEASE: "luminous"

- job:
    name: devstack-plugin-ceph-tempest-py3
    parent: devstack-plugin-ceph-tempest-py3-base
    description: |
      Integration tests that runs with the ceph devstack plugin and py3.

      This job enable the multiattach feature enable from stein on.

    # This job runs with multiattach enable from stable/stein on.
    branches: ^(?!stable/(ocata|pike|queens|rocky)).*$
    vars:
      devstack_localrc:
        ENABLE_VOLUME_MULTIATTACH: true
        CEPH_RELEASE: "nautilus"
        GANESHA_RELEASE: "V2.8-stable"

- job:
    name: devstack-plugin-ceph-compute-local-ephemeral
    parent: devstack-plugin-ceph-tempest-py3-base
    description: |
      Integration tests that runs with the ceph devstack plugin and py3.

      This job does not configure Nova to use rbd for ephemeral storage. It
      also enables the direct download of images via rbd into the local
      imagecache for Nova.
    vars:
      devstack_local_conf:
        post-config:
          $NOVA_CONF:
            glance:
              enable_rbd_download: True
              rbd_user: glance
              rbd_ceph_conf: /etc/ceph/ceph.conf
              rbd_pool: images
            libvirt:
              images_type: default

- job:
    name: devstack-plugin-ceph-tempest-ussuri-py3
    parent: devstack-plugin-ceph-tempest-py3
    override-checkout: stable/ussuri

- job:
    name: devstack-plugin-ceph-tempest-train-py3
    parent: devstack-plugin-ceph-tempest-py3
    override-checkout: stable/train

- job:
    name: devstack-plugin-ceph-tempest-stein-py3
    parent: devstack-plugin-ceph-tempest-py3
    override-checkout: stable/stein

- job:
    name: devstack-plugin-ceph-cephfs-native
    description: |
      Runs manila tempest plugin tests with Native CephFS as a manila back
      end (DHSS=False)
    parent: manila-tempest-plugin-cephfs-native

- job:
    name: devstack-plugin-ceph-cephfs-nfs
    description: |
      Runs manila tempest plugin tests with CephFS via NFS-Ganesha as a manila
      back end (DHSS=False)
    parent: manila-tempest-plugin-cephfs-nfs

- job:
    name: devstack-plugin-ceph-tempest-fedora-latest
    parent: devstack-plugin-ceph-tempest-py3
    description: |
      Integration tests that runs with the ceph devstack plugin on Fedora.
    nodeset: devstack-single-node-fedora-latest
    voting: false


- project-template:
    name: devstack-plugin-ceph-tempest-jobs
    description: |
      Runs devstack-plugin-ceph-tempest jobs.
    check:
      jobs:
        - devstack-plugin-ceph-tempest-py3
        - devstack-plugin-ceph-cephfs-native:
            irrelevant-files: *irrelevant-files
            voting: false
        - devstack-plugin-ceph-cephfs-nfs:
            irrelevant-files: *irrelevant-files
            voting: false
        - devstack-plugin-ceph-tempest-fedora-latest
    gate:
      jobs:
        - devstack-plugin-ceph-tempest-py3

- project:
    templates:
      - devstack-plugin-ceph-tempest-jobs
      - publish-openstack-docs-pti
    check:
      jobs:
        - openstack-tox-bashate
    gate:
      jobs:
        - openstack-tox-bashate
    experimental:
      jobs:
        - devstack-plugin-ceph-tempest-ussuri-py3
        - devstack-plugin-ceph-tempest-train-py3
        - devstack-plugin-ceph-tempest-stein-py3
        - devstack-plugin-ceph-compute-local-ephemeral
