- job:
    name: devstack-plugin-ceph-tempest-py3-base
    abstract: true
    parent: tempest-full-py3
    nodeset: openstack-single-node-jammy
    description: |
      Base integration tests that runs with the ceph devstack plugin and py3.
      Former names for this job where:
        * legacy-tempest-dsvm-py35-full-devstack-plugin-ceph
        * gate-tempest-dsvm-py35-full-devstack-plugin-ceph-ubuntu-xenial-nv
      The original job included support for an un-used tempest-dsvm-ceph-rc
      hosted at /opt/stack/new/nova/devstack/tempest-dsvm-ceph-rc.
    required-projects:
      - openstack/cinder-tempest-plugin
      - openstack/devstack-plugin-ceph
    irrelevant-files: &irrelevant-files
      - ^.*\.rst$
      - ^doc/.*$
      - ^tox.ini$
    timeout: 7200
    vars:
      configure_swap_size: 8192
      tempest_concurrency: 3
      devstack_localrc:
        ENABLE_FILE_INJECTION: false
        TEMPEST_PLUGINS: '/opt/stack/cinder-tempest-plugin'
        ENABLE_VOLUME_MULTIATTACH: false
        TEMPEST_RUN_VALIDATION: True
        MYSQL_REDUCE_MEMORY: True
      devstack_plugins:
        devstack-plugin-ceph: https://opendev.org/openstack/devstack-plugin-ceph
      devstack_services:
        # Disable horizon (inherited from the parent, not needed by the tests executed here)
        horizon: false
      tox_envlist: all
      tempest_test_regex: |
              (^tempest\.(api|scenario\.test_encrypted_cinder_volumes|scenario\.test_volume|scenario\.test_shelve_instance)|(^cinder_tempest_plugin))
      tempest_test_blacklist: '{{ ansible_user_dir }}/{{ zuul.projects["opendev.org/openstack/devstack-plugin-ceph"].src_dir }}/tempest_skiplist.txt'

- job:
    name: devstack-plugin-ceph-tempest-py3
    parent: devstack-plugin-ceph-tempest-py3-base
    description: |
      Integration tests that runs with the ceph devstack plugin and py3.

      This job enable the multiattach feature enable from stein on.
    vars:
      devstack_localrc:
        DISABLE_CEPHADM_POST_DEPLOY: True
        CEPHADM_DEPLOY: True

- job:
    name: devstack-plugin-ceph-compute-local-ephemeral
    parent: devstack-plugin-ceph-tempest-py3-base
    description: |
      Integration tests that runs with the ceph devstack plugin and py3.

      This job does not configure Nova to use rbd for ephemeral storage. It
      also enables the direct download of images via rbd into the local
      imagecache for Nova.
    vars:
      devstack_local_conf:
        post-config:
          $NOVA_CONF:
            glance:
              enable_rbd_download: True
              rbd_user: glance
              rbd_ceph_conf: /etc/ceph/ceph.conf
              rbd_pool: images
            libvirt:
              images_type: default

- job:
    name: devstack-plugin-ceph-cephfs-native
    description: |
      Runs manila tempest plugin tests with Native CephFS as a manila back
      end (DHSS=False)
    parent: manila-tempest-plugin-cephfs-native-cephadm

- job:
    name: devstack-plugin-ceph-cephfs-nfs-standalone
    description: |
      Runs manila tempest plugin tests with CephFS via NFS-Ganesha as a manila
      back end (DHSS=False). The Ceph cluster is created with cephadm
      while nfs-ganesha is installed "standalone" via a package.
    parent: manila-tempest-plugin-cephfs-nfs

- job:
    name: devstack-plugin-ceph-multinode-cephfs-nfs-cephadm
    parent: manila-tempest-plugin-multinode-cephfs-nfs-cephadm
    description: Test CephFS NFS (DHSS=False) in a Multinode devstack env

- job:
    name: devstack-plugin-ceph-multinode-tempest-py3
    parent: tempest-multinode-full-py3
    description: |
      Integration tests that runs the ceph device plugin across multiple
      nodes on py3. The Ceph deployment strategy used by this job is Cephadm.
    required-projects:
      - openstack/cinder-tempest-plugin
      - openstack/devstack-plugin-ceph
    timeout: 10800
    vars:
      configure_swap_size: 8192
      tempest_concurrency: 3
      devstack_localrc:
        ENABLE_FILE_INJECTION: false
        ENABLE_VOLUME_MULTIATTACH: true
        TEMPEST_RUN_VALIDATION: true
        USE_BLOCK_MIGRATION_FOR_LIVE_MIGRATION: false
        CEPHADM_DEPLOY: True
        DISABLE_CEPHADM_POST_DEPLOY: True
        MYSQL_REDUCE_MEMORY: True
        REMOTE_CEPH: False
        CINDER_CEPH_UUID: d531d2d4-3937-429c-b0c2-658fe41e82aa
      devstack_plugins:
        devstack-plugin-ceph: https://opendev.org/openstack/devstack-plugin-ceph
      devstack_services:
        # Disable horizon (inherited from the parent, not needed by the tests executed here)
        horizon: false
      tox_envlist: all
      tempest_plugins:
        - cinder-tempest-plugin
      tempest_test_regex: |
        (^tempest\.(api|scenario\.test_encrypted_cinder_volumes|scenario\.test_volume|scenario\.test_shelve_instance)|(^cinder_tempest_plugin))
      tempest_test_blacklist: '{{ ansible_user_dir }}/{{ zuul.projects["opendev.org/openstack/devstack-plugin-ceph"].src_dir }}/tempest_skiplist_multinode.txt'
    group-vars:
      subnode:
        devstack_localrc:
          REMOTE_CEPH: True
          CEPHADM_DEPLOY: True
          CINDER_CEPH_UUID: d531d2d4-3937-429c-b0c2-658fe41e82aa

- job:
    name: devstack-plugin-ceph-master-tempest
    parent: devstack-plugin-ceph-tempest-py3-base
    description: |
      Integration tests that runs with the ceph devstack plugin
      using Ceph master as the backend.
    branches: master
    vars:
      devstack_localrc:
        TEST_MASTER: true

- project-template:
    name: devstack-plugin-ceph-tempest-jobs
    description: |
      Runs devstack-plugin-ceph-tempest jobs.
    check:
      jobs:
        - devstack-plugin-ceph-tempest-py3:
            voting: false
        - devstack-plugin-ceph-tempest-cephadm:
            voting: false
        - devstack-plugin-ceph-multinode-tempest-py3
        - devstack-plugin-ceph-multinode-cephfs-nfs-cephadm
        - devstack-plugin-ceph-cephfs-native:
            irrelevant-files: *irrelevant-files
            voting: false
        - devstack-plugin-ceph-cephfs-nfs-standalone:
            irrelevant-files: *irrelevant-files
            voting: false
        # - devstack-plugin-ceph-tempest-fedora-latest
        # - devstack-plugin-ceph-multinode-tempest-py3
        # - devstack-plugin-ceph-multinode-tempest-cephadm:
        #     voting: false
        # - devstack-plugin-ceph-master-tempest:
        #     voting: false
    gate:
      jobs:
        - devstack-plugin-ceph-tempest-py3

- project:
    templates:
      - devstack-plugin-ceph-tempest-jobs
      - publish-openstack-docs-pti
    check:
      jobs:
        - openstack-tox-bashate
    gate:
      jobs:
        - openstack-tox-bashate
    experimental:
      jobs:
        - devstack-plugin-ceph-compute-local-ephemeral
