[[local|localrc]]
ADMIN_PASSWORD=secret
DATABASE_PASSWORD=root
RABBIT_PASSWORD=secret
SERVICE_PASSWORD=secret
INSTALL_TEMPEST=False
LOGFILE=/opt/stack/devstack.log
LOG_COLOR=True
VERBOSE=True
SERVICE_TIMEOUT=600

# Change Ceph Version by changing tag in CONTAINER_IMAGE.
# Supported versions are:
#   reef: quay.io/ceph/ceph:v18
#   squid: quay.io/ceph/ceph:v19
#   tentacle: quay.io/ceph/ceph:v20
# CONTAINER_IMAGE=quay.io/ceph/ceph:v20


# Override HOST_IP to private IP address if public IP is auto-detected
HOST_IP=
# Setup Ceph with Rados Gateway
RGW_PORT="8086"
ENABLE_CEPH_CINDER=True     # ceph backend for cinder
ENABLE_CEPH_GLANCE=True     # store images in ceph
ENABLE_CEPH_C_BAK=True      # backup volumes to ceph
ENABLE_CEPH_NOVA=True       # allow nova to use ceph resources
# ENABLE_CEPH_MANILA=True     # allow manila to use CephFS as backend (Native CephFS or CephFS via NFS)
ENABLE_CEPH_RGW=True
CINDER_TARGET_HELPER=tgtadm

ENABLED_SERVICES=",-horizon,-tempest,-dstat"
disable_service horizon tempest
enable_service key rabbit mysql c-bak c-api c-vol c-sch n-api n-crt n-cpu n-cond n-sch n-api-meta n-sproxy placement-api placement-client
enable_plugin devstack-plugin-ceph https://opendev.org/openstack/devstack-plugin-ceph
